- name: Install root CA and change machine SSL certificate
  hosts: all,!localhost
  strategy: free
  gather_facts: false
  become: true
  become_method: runas
  become_user: adm_win_acc
  tasks:
    - name: Test server connectivity
      ansible.windows.win_ping:
      register: ping_status
      ignore_unreachable: true
      
    - name: Check if the server is online or not
      ansible.builtin.assert:
        that:
          - ping_status.unreachable is undefined
        quiet: true

    - name: run role
      ansible.builtin.include_role:
        name: ssl_role_vcenter
      vars:
        vcenter_server: "vcenter01.local.com"
        ca_cert_path: "C:\\Users\\diego.velasquez_rem\\Desktop\\ansible-test\\ca_root_pem.pem"
        machine_ssl_cert_path: "C:\\Users\\diego.velasquez_rem\\Desktop\\ansible-test\\certnew.cer"
