---
- name: Set custom mode, reboot vCenter, and manage ESXi certificate
  hosts: vcenter_host
  gather_facts: false
  roles:
    - ssl_role_esxi
  vars:
    vcenter_server: "vcenter01.local.com"
    vcenter_user: "administrator@vsphere.local"
    vcenter_password: "!Passw0rd"
    script_dir: "C:\\temp"
    esxi_host: "esx010.local.com"
    esxi_user: "root"
    esxi_password: "!Passw0rd"
    esxi_cert_path: "C:\\Temp\\esxi_cert.pem"
    datacenter_location: "My Datacenter"
 